apiVersion: v1
kind: Service
metadata:
  name: trivia-backend
  labels:
    app: trivia-backend
    env: {{ .Values.env }}
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app: trivia-backend
    env: {{ .Values.env }}