apiVersion: v1
kind: Service
metadata:
  name: trivia-frontend
  labels:
    env: {{ .Values.env }}
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app: trivia-frontend
    env: {{ .Values.env }}